#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE09FEF25D96484AC (mcepl@suse.cz)
#
Name     : rope
Version  : 0.18.0
Release  : 25
URL      : https://files.pythonhosted.org/packages/55/50/8f9872255a2e251203991417fe6501ac2673a71613f79098d61b45733dbc/rope-0.18.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/55/50/8f9872255a2e251203991417fe6501ac2673a71613f79098d61b45733dbc/rope-0.18.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/55/50/8f9872255a2e251203991417fe6501ac2673a71613f79098d61b45733dbc/rope-0.18.0.tar.gz.asc
Summary  : a python refactoring library...
Group    : Development/Tools
License  : LGPL-3.0
Requires: rope-license = %{version}-%{release}
Requires: rope-python = %{version}-%{release}
Requires: rope-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
.. _GitHub python-rope / rope: https://github.com/python-rope/rope
========================================
rope, a python refactoring library ...
========================================

%package license
Summary: license components for the rope package.
Group: Default

%description license
license components for the rope package.


%package python
Summary: python components for the rope package.
Group: Default
Requires: rope-python3 = %{version}-%{release}

%description python
python components for the rope package.


%package python3
Summary: python3 components for the rope package.
Group: Default
Requires: python3-core
Provides: pypi(rope)

%description python3
python3 components for the rope package.


%prep
%setup -q -n rope-0.18.0
cd %{_builddir}/rope-0.18.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602176348
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rope
cp %{_builddir}/rope-0.18.0/COPYING %{buildroot}/usr/share/package-licenses/rope/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rope/a8a12e6867d7ee39c21d9b11a984066099b6fb6b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
