#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rope
Version  : 0.16.0
Release  : 20
URL      : https://files.pythonhosted.org/packages/e9/5c/59932a44f0f2b2c9e116682f11cac3b06c45ce8dca5eef355d8774d4b79c/rope-0.16.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e9/5c/59932a44f0f2b2c9e116682f11cac3b06c45ce8dca5eef355d8774d4b79c/rope-0.16.0.tar.gz
Summary  : a python refactoring library...
Group    : Development/Tools
License  : LGPL-3.0
Requires: rope-license = %{version}-%{release}
Requires: rope-python = %{version}-%{release}
Requires: rope-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
.. _GitHub python-rope / rope: https://github.com/python-rope/rope
========================================
rope, a python refactoring library ...
========================================

%package license
Summary: license components for the rope package.
Group: Default

%description license
license components for the rope package.


%package python
Summary: python components for the rope package.
Group: Default
Requires: rope-python3 = %{version}-%{release}

%description python
python components for the rope package.


%package python3
Summary: python3 components for the rope package.
Group: Default
Requires: python3-core

%description python3
python3 components for the rope package.


%prep
%setup -q -n rope-0.16.0
cd %{_builddir}/rope-0.16.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578945775
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rope
cp %{_builddir}/rope-0.16.0/COPYING %{buildroot}/usr/share/package-licenses/rope/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rope/a8a12e6867d7ee39c21d9b11a984066099b6fb6b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
